# Wokwi Configuration File
# Reference: https://docs.wokwi.com/vscode/project-config
[wokwi]
version = 1
firmware = '../../build.esp32_c3_lcdkit/flasher_args.json'
elf = '../../build.esp32_c3_lcdkit/esp32-swift-weather-display.elf'
# gdbServerPort=3333
